### ISSUE TITLE
405 Not allowed

### ISSUE THREAD

**Issue by kai23** [numberly/mattermost-integration-giphy#13]
Hi all, 

I've installed Mattermost 3.1.0 and wanted the giphy integration, but I'm struggled with a 405 Not Allowed :( 

```
[2016-06-28 17:13:44,794] [INFO] 127.0.0.1 - - [28/Jun/2016 17:13:44] "POST / HTTP/1.1" 405 -
```

If someone could lead me to a solution.

I'm on Ubuntu Trusty 14.04
Request 2.10.0

**Comment by tophat1720** [comment]
"Command with a trigger of 'gif' returned response 405 METHOD NOT ALLOWED"

**Comment by tophat1720** [comment]
I have same issue

**Comment by ramnes** [comment]
Hey guys, sorry for not answering faster, we'll try to investigate this issue as soon as possible.

Meanwhile, feel free to check if a previous version doesn't have this problem and if so, please report it back here.

**Comment by Lujeni** [comment]
Hello @kai23 ,

Did you have some logs?
Are you on heroku ?

Thanks

**Comment by dabates** [comment]
I have also run into this today as well.. 
Log:

> [2016-09-01 11:27:43,996] [INFO] xxxxxxx - - [01/Sep/2016 11:27:43] "POST / HTTP/1.1" 405 -

I'm going to tinker in the code to try and fix it.

**Comment by kobanator** [comment]
I just ran into the same issue, so just double check that your POST is going to `http://<some ip>/new_post` instead of `http://<some ip>/`

**Comment by psyc0** [comment]
have the same problem, running on the same host as mattermost with flask on :5000 , so I set the request to http://10.0.0.1:5000/new_post , also without but no luck with either.. 
```
curl 10.0.0.1:5000/new_post
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>405 Method Not Allowed</title>
<h1>Method Not Allowed</h1>
<p>The method is not allowed for the requested URL.</p>
curl 10.0.30.69:5000
OK
```
but i dont see anything trigger from the outgoing webhook if i use the one without new_post

**Comment by Lujeni** [comment]
@dabates @kobanator @tomtruitt 

Can you show me your heroku `config vars` in the `settings` part ?

Thanks

**Comment by tophat1720** [comment]
I wasn't using docker not heroku also i turned over access to the forum owner. it was working fine for me after correcting the settings i noted in my earlier comment

Tom Truitt
Liberty Vending, LLC

 
This electronic mail message contains information that (a) is or may be LEGALLY PRIVILEGED, CONFIDENTIAL, PROPRIETARY IN NATURE, OR OTHERWISE PROTECTED BY LAW FROM DISCLOSURE, and (b) is intended only for the use of the Addressee(s) named herein. If you are not the intended recipient, addressee, or the person responsible for delivering this to an addressee, you are hereby notified that reading, using, copying, or distributing any part of this message is strictly prohibited. If you have received this electronic mail message in error, please contact us immediately and take the steps necessary to delete the message completely from your computer system.

-------- Original message --------From: Lujeni notifications@github.com Date: 9/19/16  11:26 AM  (GMT-05:00) To: numberly/mattermost-integration-giphy mattermost-integration-giphy@noreply.github.com Cc: tomtruitt tom@coinkit.io, Mention mention@noreply.github.com Subject: Re: [numberly/mattermost-integration-giphy] 405 Not allowed (#13) 
@dabates @kobanator @tomtruitt 

Can you show me your heroku config vars in the settings part ?

Thanks

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/numberly/mattermost-integration-giphy","title":"numberly/mattermost-integration-giphy","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/numberly/mattermost-integration-giphy"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Lujeni in #13: @dabates @kobanator @tomtruitt \r\n\r\nCan you show me your heroku `config vars` in the `settings` part ?\r\n\r\nThanks"}],"action":{"name":"View Issue","url":"https://github.com/numberly/mattermost-integration-giphy/issues/13#issuecomment-248025940"}}}

**Comment by tophat1720** [comment]
Oh I apologize I I thought this was another issue... I no longer have access to the installation sorry can't be of assistance

**Comment by rkopplin** [comment]
could it be that the webserver is not handling POST requests?
same issue here...

 /api/v3/teams/7o8pip9hjfg7bdr74gynrmczpc/commands/execute:command code=500 rid=8mw1tu64wtrs9dhes79pfgpkuo uid=q4uxbaf1kfn69n1x4mzqtxb7ao ip=xxxxxxxx Command with a trigger of 'gif' returned response 405 METHOD NOT ALLOWED [details: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>405 Method Not Allowed</title>

<h1>Method Not Allowed</h1>

<p>The method is not allowed for the requested URL.</p>

running without heruko.

**Comment by Lujeni** [comment]
Hello @rkopplin ,

Can you give me your `env` pls? `GIPHY_API_KEY` is set ?

**Comment by rkopplin** [comment]
running un RHEL 7.
MATTERMOST_GIPHY_TOKEN is set with token id from outgoing webhook.
and giphy_api_key (beta)

bash_profile = 

export MATTERMOST_GIPHY_TOKEN=xxxxxxxxxxxxxxxxxxxxxxxxxxxxx
export MATTERMOST_GIPHY_PORT=5000
export MATTERMOST_GIPHY_HOST=0.0.0.0
export GIPHY_API_KEY=dc6zaTOxFJmzC

**Comment by Lujeni** [comment]
@rkopplin Can you give me your callback URL ?

**Comment by rkopplin** [comment]
https://most.myfirm-internalurl.com/new_post

**Comment by baudettespiria** [comment]
Hi all, 

This is working for someone ? I have the same issue with the integration.

**Comment by hoplaventure** [comment]
Hi all,

I'm the same pb. Have you a solution now ?

thx

**Comment by Lujeni** [comment]
@baudettespiria @hoplaventure @rkopplin 

Hello,

It's pretty hard to debug without context.
To help us, can you give:
- [ ] heroku or linux install
- [ ] your environment variables
- [ ] the result of these commands

``` bash
$ curl http(s)://<your_domain>/
$ curl -X POST http(s)://<your_domain>/new_post
```
- [ ] the application logs

**DISCLAIMER - We have updated the documentation which used the wrong name variable (`MATTERMOST_TOKEN` instead of `MATTERMOST_GIPHY_TOKEN`)**.

**Comment by hanzei** [comment]
@Lujeni 
Hello,
i'm having the same problem. Here is my setup:
Linux install
Mattermost-Version: 3.5
Domain: mattermost.cjf-berlin.de
Callback URLs: http://mattermost.cjf-berlin.de:62390
export MATTERMOST_GIPHY_TOKEN=XXXXX
export MATTERMOST_GIPHY_PORT=62390
export MATTERMOST_GIPHY_HOST=0.0.0.0

```
$ curl http://mattermost.cjf-berlin.de/
<!DOCTYPE html> <html> <head> <meta http-equiv=X-UA-Compatible content="IE=edge"> <meta name=viewport content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=0"> <meta name=robots content="noindex, nofollow"> <meta name=referrer content=no-referrer> <title>Mattermost</title> <meta name=apple-mobile-web-app-capable content=yes> <meta name=apple-mobile-web-app-status-bar-style content=default> <meta name=mobile-web-app-capable content=yes> <meta name=apple-mobile-web-app-title content=Mattermost> <meta name=application-name content=Mattermost> <meta name=format-detection content="telephone=no"> <link rel=apple-touch-icon sizes=57x57 href=/static/files/787db8d8b82538cc1d5e8bcb8c21722d.png> <link rel=apple-touch-icon sizes=60x60 href=/static/files/cd9987714f4d92336c3ab203ff150a9a.png> <link rel=apple-touch-icon sizes=72x72 href=/static/files/1728fd5a009aabc77654b1f958c6f596.png> <link rel=apple-touch-icon sizes=76x76 href=/static/files/17cb12b7fc37d8229a6e72f3d6da0949.png> <link rel=apple-touch-icon sizes=144x144 href=/static/files/fba6362db1d8b3e27c9fb02fd0695c85.png> <link rel=apple-touch-icon sizes=120x120 href=/static/files/08959a08dc2488dfeb8660fc4630b145.png> <link rel=apple-touch-icon sizes=152x152 href=/static/files/bca263be9acd1df84b988b02c621b8ca.png> <link rel=icon type=image/png sizes=16x16 href=/static/files/532142b052832f94ffc35860545a7e5c.png> <link rel=icon type=image/png sizes=32x32 href=/static/files/c220e89731c31367c0f4e86e3442bee0.png> <link rel=icon type=image/png sizes=96x96 href=/static/files/173682cef105829829a008f1fc97e980.png> <link rel=icon type=image/png sizes=192x192 href=/static/files/0d367a00a16bde58f7e87c4481516a68.png> <link rel=manifest href=/static/files/fee9721a6305a49662a40ffd052a7965.json> <link rel=stylesheet class=code_theme> <script type="text/javascript" src="/static/main.ee08a0c6f181e7431bd9.js"></script></head> <body> <div id=root> <div class=loading-screen style=position:relative> <div class=loading__content> <div class="round round-1"></div> <div class="round round-2"></div> <div class="round round-3"></div> </div> </div> </div> <script>window.setup_root()</script> <noscript> To use Mattermost, please enable JavaScript. </noscript> </body> </html>
$ curl -X POST http://mattermost.cjf-berlin.de/new_post
HTTP/1.1 404 Not Found
$ curl -X POST localhost:62390
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>405 Method Not Allowed</title>
<h1>Method Not Allowed</h1>
<p>The method is not allowed for the requested URL.</p>

```
Mattermost Logs:
```
[2016/11/22 09:47:42 CET][EROR] /api/v3/teams/nanc4ec8qtfdbpq566pwbi4zww/commands/execute:command code=500 rid=dnndzfqmdbgm9jwaopggf1bm6e uid=zfm7ekht67b6zrr85itburpz6e ip=XXX.XXX.XXX.XXX, 127.0.0.1 Befehl mit dem Trigger 'gif' gibt den Wert 405 METHOD NOT ALLOWED zurück [Details: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>405 Method Not Allowed</title>
<h1>Method Not Allowed</h1>
<p>The method is not allowed for the requested URL.</p>
]
[2016/11/22 09:47:52 CET] [EROR] /api/v3/teams/nanc4ec8qtfdbpq566pwbi4zww/channels/null/posts/page/0/60:getPosts code=400 rid=8smigi4gy78wfmwa5uoa7rd45e uid=um3ick45578mffzhmzs5ktua4o ip=XXX.XXX.XXX.XXX, 127.0.0.1 Invalid channelId parameter [Details: ]
```

**Comment by chakatz** [comment]
I seem to be having the same problem.
First a few points for clarification...

1. Am I REQUIRED to configure BOTH the "outgoing webhooks" AND the "slash command"?
2. My server runs on https but port 5000 is not on https so I assume I need to use http in the URLs.
3. Do I need to include the port in the URL in the "outgoing webhooks" and "slash command" configuration?
4. Which token goes into .bashrc, the "outgoing webhooks" token or the "slash command" token?

Linux
Mattermost Version: 3.5.0

export MATTERMOST_GIPHY_TOKEN=123123123123123
export MATTERMOST_GIPHY_HOST=0.0.0.0
export MATTERMOST_GIPHY_PORT=5000

```
$ curl -X POST http://mattermost.example.org:5000/new_post
{"username": "giphy", "icon_url": "https://avatars0.githubusercontent.com/u/3588525?v=3&s=200", "text": "Missing necessary token in the post data"}

$ curl http://mattermost.example.org:5000/
OK
```

```
platform[28239]: [2016/11/30 18:22:16 UTC] [EROR] /api/v3/teams/uuzqjjrzyifbddwhz68iuhcc5h/commands/execute:command code=500 rid=mwigbn41jbyr5jqmeh9wgzhf8w uid=g8ngu5u4q7nx8m547pik4mamrw ip=xxx.xxx.xxx.xxx Command with a trigger of 'giphy' returned response 405 METHOD NOT ALLOWED [details: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
platform[28239]: <title>405 Method Not Allowed</title>
platform[28239]: <h1>Method Not Allowed</h1>
platform[28239]: <p>The method is not allowed for the requested URL.</p>
platform[28239]: ]
```

**Comment by Lujeni** [comment]
Hello,

The first documentation are a little bit cluttered.
imho, this MR will clarify the documentation https://github.com/numberly/mattermost-integration-giphy/pull/20:
- outgoing webhook part is useless (only keep tslash).
- in the slash command documentation, the callback url was bad (missing the new_post endpoint).

@Hanzei 
the right callback url must be:
http://mattermost.cjf-berlin.de:62390/new_post

@chakatz 

>    Am I REQUIRED to configure BOTH the "outgoing webhooks" AND the "slash command"?

Not only the slash command is necessary.

>    My server runs on https but port 5000 is not on https so I assume I need to use http in the URLs.
    Do I need to include the port in the URL in the "outgoing webhooks" and "slash command" configuration?

yep with `new_post` at the end.

>    Which token goes into .bashrc, the "outgoing webhooks" token or the "slash command" token?

only the slash token

Thanks

**Comment by hanzei** [comment]
@Lujeni Thanks this fixed my problem :+1:

**Comment by chakatz** [comment]
@Lujeni The new instructions resolved my problem as well! :-) :+1:

**Comment by hanzei** [comment]
#20 also added a new instructions. We can close this one now, cant we?

**Comment by Lujeni** [comment]
> #20 also added a new instructions. We can close this one now, cant we?

yep. Thanks

**Comment by debaser19** [comment]
Sorry to re-open this, seems like it might be related. I've configured everything according to the Linux install, Ubuntu 16.04. When i try the slash command in mattermost, i get `Command with a trigger of 'gif' failed`

I have the /new_post tacked on to the end of the url

Server shows this error
`code 400, message Bad request syntax ('\x16\x03\x01\x00\x9e\x01\x00\x00\x9a\x03\x03E\xc8K\xbe\xeb\t\xd8\t\xf1\x03o\x0e\xf9X\x89\xf2w\xa3\xc1R\x0eG\x05r9\x88b@\xf4d)\x0b\x00\x00 \xc0/\xc00\xc0+\xc0,\xcc\xa8\xcc\xa9\xc0\x13\xc0\t\xc0\x14\xc0')`

any ideas?
